services:
  klipper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: klipper-service

    # Add device cgroup rule for serial access
    device_cgroup_rules:
      - 'c 166:* rmw'  # ttyACM devices
      - 'c 188:* rmw'  # ttyUSB devices

    volumes:
      # Mount Klipper source code
      - ./klipper:/opt/klipper:rw

      # Mount configuration
      - ./config:/opt/printer_data/config:rw

      # Mount serial devices directory
      - /dev/serial:/dev/serial:rw
      - /dev/ttyACM0:/dev/ttyACM0:rw
      - /dev/ttyUSB0:/dev/ttyUSB0:rw

      # Shared socket directory for moonraker
      - klipper-socket:/tmp/klipper

      # Logs
      - ./logs:/opt/printer_data/logs

      - ./gcodes:/opt/printer_data/gcodes:rw

    network_mode: host

    working_dir: /opt/klipper

    # Run Klipper service
    #command: /bin/bash -c "tail -f /dev/null"
    # Run Klipper service
    command: /opt/venv/bin/python /opt/klipper/klippy/klippy.py /opt/printer_data/config/printer.cfg -l /opt/printer_data/logs/klippy.log -a /tmp/klipper/klippy.sock
    # /opt/venv/bin/python /opt/klipper/klippy/klippy.py /opt/printer_data/config/printer.cfg -a /tmp/klipper/klippy.sock

    restart: unless-stopped

    environment:
      - PYTHONUNBUFFERED=1

    group_add:
      - dialout

    # Limit resources for production use
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  moonraker:
    image: mkuf/moonraker:latest
    container_name: moonraker
    depends_on:
      - klipper
    network_mode: host

    volumes:
      # Configuration
      - ./config:/opt/printer_data/config:rw

      # Moonraker database
      - moonraker-db:/opt/moonraker/database

      # G-code files
      - ./gcodes:/opt/printer_data/gcodes:rw

      # Shared socket with Klipper
      - klipper-socket:/tmp/klipper:rw

      # Logs
      - ./logs:/opt/printer_data/logs

    restart: unless-stopped

    environment:
      - PYTHONUNBUFFERED=1

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:latest
    container_name: mainsail
    depends_on:
      - moonraker
    network_mode: host

    restart: unless-stopped

    volumes:
      - ./config/mainsail-config.json:/usr/share/nginx/html/config.json:ro
      - ./config/nginx-mainsail.conf:/etc/nginx/conf.d/default.conf:ro

    environment:
      - NGINX_LISTEN_PORT=8010  # Configure nginx to listen on 8010

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  klipper-socket:
  klipper-logs:
  moonraker-db:
  moonraker-logs:
  mainsail-config: